const menu = [{
    breakfast: [
        {
            id: 001,
            name: "Grilled Fillet",
            price: 12.95,
            img: "",
            fill: "Eggs, bacon and cherry-tomatoes with bread",
            description: "",
            detail: {},
        }, {
            id: 002,
            name: "Alder grilled seafood paella",
            price: 19.95,
            img: "",
            fill: "Oat granola with fresh blueberries, almond, yogurt",
            description: "",
            detail: {},
        }, {
            id: 003,
            name: "Chicken Breast",
            price: 14.95,
            img: "",
            fill: "Applewood smoked bacon,tomatoes & green",
            description: "",
            detail: {},
        }, {
            id: 004,
            name: "Sea Trout",
            price: 15.95,
            img: "",
            fill: "Salmon, butter, lemon juice, onion, garlic & salad",
            description: "",
            detail: {},
        }, {
            id: 005,
            name: "Sea Trout",
            price: 15.95,
            img: "",
            fill: "Salmon, butter, lemon juice, onion, garlic & salad",
            description: "",
            detail: {},

        }, {
            id: 006,
            name: "Roasted Steak Roulade",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},
        }
    ],
    lunch: [
        {
            id: 007,
            name: "Meat Ball Soup",
            price: 12.95,
            img: "",
            fill: "Eggs, bacon and cherry-tomatoes with bread",
            description: "",
            detail: {},
        }, {
            id: 008,
            name: "Grilled American Fillet",
            price: 19.95,
            img: "",
            fill: "Oat granola with fresh blueberries, almond, yogurt",
            description: "",
            detail: {},
        }, {
            id: 009,
            name: "Grilled Seafood paella",
            price: 14.95,
            img: "",
            fill: "Applewood smoked bacon, tomatoes & green",
            description: "",
            detail: {},

        }, {
            id: 010,
            name: "Roast Sea trout",
            price: 15.95,
            img: "",
            fill: "Salmon, butter, lemon juice, onion, garlic & salad",
            description: "",
            detail: {},

        }, {
            id: 011,
            name: "Smoked paprika hum",
            price: 12.95,
            img: "",
            fill: "Baguette, basil, arugula, olives, cherry-tomatoes",
            description: "",
            detail: {},

        }, {
            id: 012,
            name: "Oyster with hot sauce",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},

        }, {
            id: 013,
            name: "Meat Ball Soup",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},

        }, {
            id: 014,
            name: "Grilled American fillet",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},

        }, {
            id: 015,
            name: "Roast Sea Trout",
            price: 16.95,
            img: "",
            fill: "Salmon, butter, lemon juice, onion, garlic & salad",
            description: "",
            detail: {},

        }, {
            id: 016,
            name: "Roast Sea Trout",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},

        }, {
            id: 017,
            name: "Smoked Paprika Hum",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},

        }, {
            id: 018,
            name: "Oyster with hot sauce",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},
        }
    ],
    dinner: [
        {
            id: 019,
            name: "Grilled fillet",
            price: 12.95,
            img: "",
            fill: "eggs, bacon and cherry-tomotoes with bread",
            description: "",
            detail: {},
        },{
            id: 020,
            name: "Alder Grilled Seafood Paella",
            price: 19.95,
            img: "",
            fill: "Oat granota with fresh blueberries almond, yogurt",
            description: "",
            detail: {},
        },{
            id: 021,
            name: "Chicken Breast",
            price: 14.95,
            img: "",
            fill: "Applewood smoked bacon, tomatoes & green",
            description: "",
            detail: {},
        },{
            id: 022,
            name: "Sea Trout",
            price: 15.95,
            img: "",
            fill: "Salmon, butter, lemon juice, onion, garlic & salad",
            description: "",
            detail: {},
        },{
            id: 023,
            name: "Smoked paprika hummus",
            price: 12.95,
            img: "",
            fill: "Baguette, basit, arugula, olives, cherry-tomatoes",
            description: "",
            detail: {},
        },{
            id: 024,
            name: "Roasted Steak Roulade",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},
        }
    ],
    dessert: [
        {
            id: 025,
            name: "Beautiful Homemade Croissonts",
            price: 12.95,
            img: "",
            fill: "Eggs, Bacon, Cherry-tomatoes with Bread",
            description: "",
            detail: {},
        },{
            id: 026,
            name: "Blueberry Sweet Rolls",
            price: 19.95,
            img: "",
            fill: "Oat Granola with Fresh Blueberries, Almond, yogurt",
            description: "",
            detail: {},
        },{
            id: 027,
            name: "Traditional Pancakes",
            price: 14.95,
            img: "",
            fill: "Applewood Smoked Bacon, Tomatoes, Green",
            description: "",
            detail: {},
        },{
            id: 028,
            name: "Chocolate Cherry Cake",
            price: 15.95,
            img: "",
            fill: "Salmon, Butter, Lemon Juice, Onion, Garlic, Salad",
            description: "",
            detail: {},
        },{
            id: 029,
            name: "Pain Au Chocalat",
            price: 12.95,
            img: "",
            fill: "Boguette, Basil, Arugula, Alives, Cherry Tomatoes",
            description: "",
            detail: {},
        },{
            id: 030,
            name: "Cannoli with Cream Cheese",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},
        }
    ],
    drink: [
        {
            id: 031,
            name: "Cappuccino Coffe",
            price: 12.95,
            img: "",
            fill: "Eggs, Bacon, Cherry-tomatoes with Bread",
            description: "",
            detail: {},
        },{
            id: 032,
            name: "Caffe Macchiato",
            price: 19.95,
            img: "",
            fill: "Oat Granola with Fresh Blueberries, Almond, yogurt",
            description: "",
            detail: {},
        },{
            id: 033,
            name: "Dark Coffe",
            price: 14.95,
            img: "",
            fill: "Applewood Smoked Bacon, Tomatoes, Green",
            description: "",
            detail: {},
        },{
            id: 034,
            name: "Espresso Coffe",
            price: 15.95,
            img: "",
            fill: "Salmon, Butter, Lemon Juice, Onion, Garlic, Salad",
            description: "",
            detail: {},
        },{
            id: 035,
            name: "Coffee Latte",
            price: 12.95,
            img: "",
            fill: "Boguette, Basil, Arugula, Alives, Cherry Tomatoes",
            description: "",
            detail: {},
        },{
            id: 030,
            name: "Coffe And Strawberry Jam",
            price: 20.95,
            img: "",
            fill: "Croissants with strawberries, mascarpone, honey",
            description: "",
            detail: {},
        }
    ],
}];
